### PR TITLE
fix: add keyboard shortcuts

### LINKED ISSUE #37: Keyboard navigation
It could be useful to support keyboard selection.

If you start typing "hiber" you get four results. Then if you press DOWN you get a cursor over the first result. You can move between results with UP/DOWN. Pressing ENTER over a result will select it. Pressing ESC will clear the search field. Note that you can still keep on typing to narrow the results, so the focus should not leave the text field.

If you start typing "hiber" you get four results. Then if you press ENTER you select all four.

This can wait until after the first release.

### PR DESCRIPTION
**Pull request by edewit**
use `space` to flip selection and up and down arrows

fixes #37

### CODE REVIEW

**Comment by ia3andy** [comment]
LGTM 

@edewit I hope you don't mind:
- I preferred using `space` to flip selection
- To avoid confusion, I unactivated the feature by default, it starts when the user hit up or down

File: src/main/frontend/src/code-quarkus/pickers/extensions-picker.tsx [hunk 1]
```diff
@@ -126,15 +126,29 @@ export const ExtensionsPicker = (props: ExtensionsPickerProps) => {
       analytics.event('Picker', 'Search-Extension')
     }
     setHasSearched(true);
-    setKeyBoardSelected(0);
+    setKeyBoardActived(-1);
     setFilter(f);
   }
+
+  const flip = (id: string) => {
+    console.log("flip" + id);
```
Comment (edewit) [inline src/main/frontend/src/code-quarkus/pickers/extensions-picker.tsx]: remove this debug log

Comment (ia3andy) [reply src/main/frontend/src/code-quarkus/pickers/extensions-picker.tsx]: Wow good catch !!
